name: Android CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        api-level: [21, 23, 29]
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew
     
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        script: ./gradlew connectedCheck :myencrypt:connectedAndroidTest
